### PR TITLE
New Borgs sprites

### PR DESCRIPTION
**Pull request by crvsindex**
:cl:  cvrsindex
rscadd: a new model of borg is avaible now for: engineers, miners, medical, security and engineer.

/:cl:
The new borgs sprites will be avaible now in Stratus. 
basic borg:
https://gyazo.com/d54f2947faed44af3acc0ec627a72f52
miner borg:
https://gyazo.com/06bf944efbc0da4320aca28f868120d3
medical borg:
https://gyazo.com/669e2f616205cfaafe978517a81e9aa1
sec borg:
https://gyazo.com/a710883bd1238ef68ed63b0c805ee758
engi borg: 
https://gyazo.com/8a4825b0fc2d2d3c06086c0519e54757

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
a) Please provide images so we can see what's new.
b) Please make a changelog.
c) Are those supposed to be admin-only? There's no way to access them in-game without admin tools.

**Comment by crvsindex** [comment]
ok, i see why. I ony push one of the file. wtf

**Comment by FlattestGuitar** [comment]
Terribly sorry for the delay here, I'm super busy lately.

Call the borg types something else, "Stratus" is the name of the station; shouldn't be what the modules are called.

Personally, I'm really opposed to just using robots from Fallour as our sprites; it's very silly.

References should be more indirect.

**Comment by FlattestGuitar** [comment]
Alright. Following a conversation with the dev team we've agreed the sprites won't pass as long as they're a direct reference to Fallout. I don't think any sensible amount of tweaks will make the sprites more original, but it's your call what to do with this PR.

Happy spriting!

**Pull request closed without merging**
