### PR TITLE
Guts fluff and donation items out of the code.

### PR DESCRIPTION
**Pull request by DarkPyrolord**
As it states in the title, removes all fluff items code-wise, the sprites have been left in for now, also changed a reference to Paradise over to Stratus in customitems/item_defines.dm.

No CL as this won't change anything gameplay wise.

### CODE REVIEW

**Comment by DarkPyrolord** [comment]
Damn you travis, going to close and reopen to see if it won't fail me for no reason again.

**Comment by MrFroztee** [comment]
Rippo, not sure what the issue is with this checker.

**Comment by DarkPyrolord** [comment]
`_maps/map_files/RandomZLevels/moonoutpost19.dmm:619:error: undefined type: /obj/item/clothing/suit/chaplain_hoodie`

Not even related to this PR, yet for some reason it brings it up and didn't with other PRs, only thing I can think of that would cause this is the chaplain hoodie fluff item, which shouldn't have an impact on the gateway map at all.

**Comment by DarkPyrolord** [comment]
Going to try this one more time, trav pls

**Comment by theColdflame** [comment]
Have you tried taking the hoodie out of the away mission entirely?

**Comment by DarkPyrolord** [comment]
Why are we still here, just to suffer?

**Pull request closed without merging**
